language: python
python:
  - "3.6"
services: mongodb
addons:
  apt_packages:
    - pandoc
install:
  - "pip install --upgrade -r requirements.txt"
  - "pip install --upgrade -r requirements-dev.txt"
  - make install
script: make test
after_success:
  - coveralls
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
notifications:
  slack: quokkaproject:pjF8y81mqwXxQRtf5sGz5zqr
